### ISSUE TITLE
Vendor Edit While Deleting the Attachment 

### ISSUE THREAD

**Issue by mounikaalladi** [acsestech/virtualassociate#59]
Vendor Edit While Deleting the Attachment  and not deleting and not  saving displaying Empty toast message.

![image](https://cloud.githubusercontent.com/assets/23167576/20003693/eec66bba-a2ad-11e6-8a28-5d870de89842.png)

Vendor Edit Login details also not displaying.

![image](https://cloud.githubusercontent.com/assets/23167576/20003770/43bbc17e-a2ae-11e6-8f2b-98ffb76d0631.png)

**Comment by NaziniSK** [comment]
this issue is corrected

**Comment by mounikaalladi** [comment]
This is still Not working 
![image](https://cloud.githubusercontent.com/assets/23167576/20129573/bc3af77a-a676-11e6-8134-fcfa3168efc5.png)

**Comment by mounikaalladi** [comment]
First i have attached two records and saved .
![image](https://cloud.githubusercontent.com/assets/23167576/20344016/fa2d749a-ac16-11e6-97e2-339e455d3e29.png)

Once again  i attached 2 records and saved.
![image](https://cloud.githubusercontent.com/assets/23167576/20344095/54e741e0-ac17-11e6-979b-1acdcdbe073f.png)

and then i have deleted those 2 records which i have added secondly.
![image](https://cloud.githubusercontent.com/assets/23167576/20344110/666b2aee-ac17-11e6-9fff-836085244d53.png)

 and then saved .
![image](https://cloud.githubusercontent.com/assets/23167576/20344117/6f8e2d24-ac17-11e6-93a0-3fb3366212b3.png)

After refreshed the page there i can see the previously deleted records.
![image](https://cloud.githubusercontent.com/assets/23167576/20344127/79706370-ac17-11e6-8ab7-3dda743eaa30.png)

**Comment by NaziniSK** [comment]
corrected this
1.first I deleted one record (upload.txt is deleted) and added another (VA-invoice is  added)
![image](https://cloud.githubusercontent.com/assets/23185953/20381896/7f11c9aa-accf-11e6-9bd0-74638cb2b75c.png)
and saved , I got this
![image](https://cloud.githubusercontent.com/assets/23185953/20381941/c05bc9c4-accf-11e6-8f59-4a45c5287e14.png)

then again I clicked on save, again got same success message( no blank toast or error)
